### ISSUE TITLE
Remove base.sql completely from the git 

### ISSUE THREAD

**Issue by nhsbsa-kaygo** [nhsbsa-data-analytics/nhs-low-income-scheme-scrollytell#35]
?https://stackoverflow.com/questions/13716658/how-to-delete-all-commit-history-in-github

**Comment by admivsn** [comment]
REMOVE GIT HISTORY:



git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch PATH_TO_FILE' g-name-filter cat -- --all

git push --all --force
